# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Default
  demands: unity_2021.03.10f1

steps:
- task: UnityBuildTask@3
  inputs:
    buildTarget: 'Android'
    outputPath: '$(Build.BinariesDirectory)'
    outputFileName: 'mybuild'
